openapi: 3.0.0
info:
  title: 'People Management System API'
  description: 'API for a people_management_system.'
  contact:
    name: Henry Steinhauer
    email: Henrysteinhauer@t-online.de
    url: https://github.com/H3nSte1n
  version: '1.0.0'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

paths:
  /api/v1/teams:
    get:
      tags:
        - Teams Administration
      summary: Gets all Teamens
      description: Get a list of all Teams. The list supports pagination.
      parameters:
        - in: query
          name: pageSize
          description: Teams per Page
          schema:
            type: integer
        - name: pageNumber
          in: query
          description: Page number
          schema:
            type: integer
      responses:
        '200':
          description: Returns the selected Team.
          content:
            application/json:
              allOf:
                - $ref: './components/teams.yml#definitions/Team'
                - $ref: './components/teams.yml#definitions/Team--extended'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
    post:
      tags:
        - Teams Administration
      summary: Creates a Team
      description: Adds a new Team to the Team list.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/teams.yml#definitions/Team'
      responses:
        '201':
          description: Create new Team
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './components/teams.yml#definitions/Team'
                  - $ref: './components/teams.yml#definitions/Team--extended'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
  /api/v1/teams/{team_id}:
    get:
      tags:
        - Teams Administration
      summary: Gets a selected Team
      description: Returns a single Team identified by id.
      parameters:
        - name: team_id
          in: path
          required: true
          description: Team's id
          type: number
      responses:
        '200':
          description: Returns the selected Team.
          content:
            application/json:
              schema:
                $ref: './components/teams.yml#definitions/Team'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
    delete:
      tags:
        - Teams Administration
      summary: Remove a selected Team
      description: Remove a single Team identified by id and return them.
      parameters:
        - name: team_id
          in: path
          required: true
          description: Team's id
          type: number
      responses:
        '204':
          description: Returns the removed Team.
          content:
            application/json:
              schema:
                $ref: './components/teams.yml#definitions/RemovedTeams'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'
    put:
      tags:
        - Teams Administration
      summary: Update a selected Team
      description: Update a single Team identified by id and return them.
      parameters:
        - name: team_id
          in: path
          required: true
          description: Team's id
          type: number
      requestBody:
        content:
          application/json:
            schema:
              $ref: './components/teams.yml#definitions/Team'
      responses:
        '204':
          description: return the updated Team
          content:
            application/json:
              schema:
                $ref: './components/teams.yml#definitions/Team'
        400:
          $ref: './components/errors.yml#/components/responses/BadRequest'
        401:
          $ref: './components/errors.yml#/components/responses/Unauthorized'
        500:
          $ref: './components/errors.yml#/components/responses/InternalServerError'




